#!/usr/bin/env python
"""Build and verify PythOS boot serial markers."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERIAL_LOG = ROOT / "target" / "boot-serial.log"
ISO_IMAGE = ROOT / "target" / "pythos.iso"
MARKER_ORDER_EXIT_CODE = 23
FAILURE_MARKERS = [
    "PYTHOS:LOADER:FAIL",
    "PYTHOS:PANIC",
    "PYTHOS:CORE:BOOTINFO_INVALID",
    "PYTHOS:CORE:MEMORY_INVALID",
]
SLICE_MARKERS = {
    "loader-enter": ["PYTHOS:LOADER:ENTER"],
    "gop-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
    ],
    "kernel-loaded": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
    ],
    "memory-map-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
    ],
    "exit-boot-services-ok": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
    ],
    "core-enter": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
    ],
    "bootinfo-valid": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
    ],
    "framebuffer-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:FRAMEBUFFER_READY",
    ],
    "memory-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
    ],
    "gdt-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
    ],
    "idt-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
    ],
    "vm-ready": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:VM_READY",
    ],
    "exceptions-diagnostic": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
    ],
    "exception-entry-hardening": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
    ],
    "interrupt-controller": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
    ],
    "identity-map-removed": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
    ],
    "bootinfo-complete": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
    ],
    "timer": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
    ],
    "monotonic-clock": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
    ],
    "task-structures": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
    ],
    "kernel-stacks": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
    ],
    "context-switch": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
    ],
    "scheduler": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
    ],
    "idle-task": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
    ],
    "preemption": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
    ],
    "task-termination": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
    ],
    "scheduler-tests": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDULER_TESTS_READY",
    ],
    "service-identity": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDULER_TESTS_READY",
        "PYTHOS:CORE:SERVICE_IDENTITY_READY",
    ],
    "ipc-channels": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDULER_TESTS_READY",
        "PYTHOS:CORE:SERVICE_IDENTITY_READY",
        "PYTHOS:CORE:IPC:SEND",
        "PYTHOS:CORE:IPC:RECV",
        "PYTHOS:CORE:IPC_CHANNELS_READY",
    ],
    "bounded-queues": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDULER_TESTS_READY",
        "PYTHOS:CORE:SERVICE_IDENTITY_READY",
        "PYTHOS:CORE:IPC:SEND",
        "PYTHOS:CORE:IPC:RECV",
        "PYTHOS:CORE:IPC_CHANNELS_READY",
        "PYTHOS:CORE:IPC:QUEUE_FULL",
        "PYTHOS:CORE:BOUNDED_QUEUES_READY",
    ],
    "milestone-1": [
        "PYTHOS:LOADER:ENTER",
        "PYTHOS:LOADER:GOP_READY",
        "PYTHOS:LOADER:KERNEL_LOADED",
        "PYTHOS:LOADER:MEMORY_MAP_READY",
        "PYTHOS:LOADER:EXIT_BOOT_SERVICES_OK",
        "PYTHOS:CORE:ENTER",
        "PYTHOS:CORE:BOOTINFO_VALID",
        "PYTHOS:CORE:MEMORY_READY",
        "PYTHOS:CORE:GDT_READY",
        "PYTHOS:CORE:IDT_READY",
        "PYTHOS:CORE:EXCEPTIONS_DIAGNOSTIC_READY",
        "PYTHOS:CORE:EXCEPTION_ENTRY_HARDENED",
        "PYTHOS:CORE:INTERRUPTS_READY",
        "PYTHOS:CORE:VM_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:IDENTITY_MAP_REMOVED",
        "PYTHOS:CORE:BOOTINFO_COMPLETE",
        "PYTHOS:CORE:TIMER_READY",
        "PYTHOS:CORE:CLOCK_READY",
        "PYTHOS:CORE:TASKS_READY",
        "PYTHOS:CORE:EXPECTED_PAGE_FAULT",
        "PYTHOS:CORE:KERNEL_STACKS_READY",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_A",
        "PYTHOS:CORE:CONTEXT_SWITCH:TASK_B",
        "PYTHOS:CORE:CONTEXT_SWITCH_READY",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER:TASK_A",
        "PYTHOS:CORE:SCHEDULER:TASK_B",
        "PYTHOS:CORE:SCHEDULER_READY",
        "PYTHOS:CORE:IDLE_TASK",
        "PYTHOS:CORE:IDLE_TASK_READY",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT:TASK_A",
        "PYTHOS:CORE:PREEMPT:TASK_B",
        "PYTHOS:CORE:PREEMPT_READY",
        "PYTHOS:CORE:TASK_TERMINATED",
        "PYTHOS:CORE:TASK_TERMINATION_READY",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDTEST:TASK_A",
        "PYTHOS:CORE:SCHEDTEST:TASK_B",
        "PYTHOS:CORE:SCHEDTEST:TASK_C",
        "PYTHOS:CORE:SCHEDULER_TESTS_READY",
        "PYTHOS:CORE:SERVICE_IDENTITY_READY",
        "PYTHOS:CORE:IPC:SEND",
        "PYTHOS:CORE:IPC:RECV",
        "PYTHOS:CORE:IPC_CHANNELS_READY",
        "PYTHOS:CORE:IPC:QUEUE_FULL",
        "PYTHOS:CORE:BOUNDED_QUEUES_READY",
        "PYTHOS:CORE:FRAMEBUFFER_READY",
        "PYTHOS:CORE:MILESTONE_1_COMPLETE",
    ],
}


def insert_before(markers: list[str], before: str, additions: list[str]) -> list[str]:
    index = markers.index(before)
    return markers[:index] + additions + markers[index:]


REQUEST_REPLY_MARKERS = [
    "PYTHOS:CORE:IPC:REQUEST",
    "PYTHOS:CORE:IPC:REPLY",
    "PYTHOS:CORE:IPC:REPLY_TIMEOUT",
    "PYTHOS:CORE:REQUEST_REPLY_READY",
]
CAPABILITY_HANDLE_MARKERS = [
    "PYTHOS:CORE:CAPABILITY:GRANT",
    "PYTHOS:CORE:CAPABILITY:USE",
    "PYTHOS:CORE:CAPABILITY_HANDLES_READY",
]
SHARED_MEMORY_MARKERS = [
    "PYTHOS:CORE:SHM:READ_ONLY",
    "PYTHOS:CORE:SHM:WRITE_DENIED",
    "PYTHOS:CORE:SHARED_MEMORY_HANDLES_READY",
]
PERMISSION_VALIDATION_MARKERS = [
    "PYTHOS:CORE:PERMISSION:IPC_ALLOWED",
    "PYTHOS:CORE:PERMISSION:IPC_DENIED",
    "PYTHOS:CORE:PERMISSION_VALIDATION_READY",
]
REVOCATION_MARKERS = [
    "PYTHOS:CORE:CAPABILITY:REVOKE",
    "PYTHOS:CORE:CAPABILITY:STALE_DENIED",
    "PYTHOS:CORE:REVOCATION_READY",
]
NEGATIVE_AUTHORIZATION_MARKERS = [
    "PYTHOS:CORE:CAPABILITY:KNOWN_TARGET_DENIED",
    "PYTHOS:CORE:NEGATIVE_AUTHORIZATION_READY",
]
AUDIT_LOGGING_MARKERS = [
    "PYTHOS:CORE:AUDIT:GRANT",
    "PYTHOS:CORE:AUDIT:USE",
    "PYTHOS:CORE:AUDIT:DENIAL",
    "PYTHOS:CORE:AUDIT:REVOCATION",
    "PYTHOS:CORE:AUDIT_LOGGING_READY",
    "PYTHOS:CORE:PHASE_3_COMPLETE",
]
RUNTIME_SELECTION_MARKERS = [
    "PYTHOS:CORE:RUNTIME_SELECTED",
]
INIT_PAK_LOADING_MARKERS = [
    "PYTHOS:CORE:INIT_PAK_LOADED",
]
INTERPRETER_BOOT_MARKERS = [
    "PYTHOS:CORE:INTERPRETER_BOOTED",
]
SYSTEM_API_MARKERS = [
    "PYTHOS:CORE:SYSTEM:LOG",
    "PYTHOS:CORE:SYSTEM_API_READY",
]
VALUE_VALIDATION_MARKERS = [
    "PYTHOS:CORE:VALUE_VALIDATION_READY",
]
SERVICE_MANAGER_MARKERS = [
    "PYTHOS:CORE:SERVICE:READY",
    "PYTHOS:CORE:SERVICE_MANAGER_READY",
]
EXCEPTION_CONTAINMENT_MARKERS = [
    "PYTHOS:CORE:SERVICE:EXCEPTION",
    "PYTHOS:CORE:SERVICE_EXCEPTION_CONTAINED",
]
SERVICE_RESTART_MARKERS = [
    "PYTHOS:CORE:SERVICE:RESTART",
    "PYTHOS:CORE:SERVICE_RESTART_READY",
]
ASYNC_EVENT_MARKERS = [
    "PYTHOS:CORE:SERVICE:EVENT",
    "PYTHOS:CORE:ASYNC_EVENTS_READY",
]
INPUT_DRIVER_MARKERS = [
    "PYTHOS:CORE:INPUT:KEYBOARD",
    "PYTHOS:CORE:INPUT:MOUSE",
    "PYTHOS:CORE:INPUT_DRIVERS_READY",
]
INPUT_EVENT_SERVICE_MARKERS = [
    "PYTHOS:CORE:INPUT:EVENT",
    "PYTHOS:CORE:INPUT_EVENT_SERVICE_READY",
]
SOFTWARE_RENDERER_MARKERS = [
    "PYTHOS:CORE:RENDER:RECT",
    "PYTHOS:CORE:SOFTWARE_RENDERER_READY",
]
FONT_SYSTEM_MARKERS = [
    "PYTHOS:CORE:FONT:PSF_LOADED",
    "PYTHOS:CORE:FONT_SYSTEM_READY",
]
COMPOSITOR_MARKERS = [
    "PYTHOS:CORE:COMPOSITOR:SURFACE",
    "PYTHOS:CORE:COMPOSITOR:CLIP",
    "PYTHOS:CORE:COMPOSITOR_READY",
]
WINDOW_INTERACTION_MARKERS = [
    "PYTHOS:CORE:POINTER_CURSOR_READY",
    "PYTHOS:CORE:WINDOW_FOCUS_READY",
    "PYTHOS:CORE:MOVABLE_WINDOWS_READY",
]
WIDGET_MARKERS = [
    "PYTHOS:CORE:WIDGET:BUTTON",
    "PYTHOS:CORE:WIDGET:TEXT_FIELD",
    "PYTHOS:CORE:WIDGETS_READY",
]
PHASE_5_APP_MARKERS = [
    "PYTHOS:CORE:APP:LAUNCHER",
    "PYTHOS:CORE:APP:SERVICE_MONITOR",
    "PYTHOS:CORE:APP:PYTHON_CONSOLE",
    "PYTHOS:CORE:APP:SETTINGS_PANEL",
    "PYTHOS:CORE:PHASE_5_COMPLETE",
]
AUDIO_DEVICE_SELECTION_MARKERS = [
    "PYTHOS:CORE:AUDIO:DEVICE_SELECTED",
    "PYTHOS:CORE:AUDIO_DEVICE_SELECTION_READY",
]
AUDIO_DRIVER_MARKERS = [
    "PYTHOS:CORE:AUDIO:DRIVER",
    "PYTHOS:CORE:AUDIO_DRIVER_READY",
]
AUDIO_BUFFER_MARKERS = [
    "PYTHOS:CORE:AUDIO:BUFFER",
    "PYTHOS:CORE:AUDIO_BUFFERS_READY",
]
PCM_PLAYBACK_MARKERS = [
    "PYTHOS:CORE:AUDIO:PCM_PLAYBACK",
    "PYTHOS:CORE:PCM_PLAYBACK_READY",
]
AUDIO_MIXING_MARKERS = [
    "PYTHOS:CORE:AUDIO:MIX:HISS",
    "PYTHOS:CORE:AUDIO:MIX:SUB_BASS",
    "PYTHOS:CORE:AUDIO:MIX:TREMOLO",
    "PYTHOS:CORE:AUDIO_MIXING_READY",
]
BOOT_ASSET_MARKERS = [
    "PYTHOS:CORE:BOOT_ASSET:VISUAL",
    "PYTHOS:CORE:BOOT_ASSET:PCM",
    "PYTHOS:CORE:BOOT_ASSET:SYNC",
    "PYTHOS:CORE:BOOT_ASSETS_READY",
]
AUDIO_VISUAL_SYNC_MARKERS = [
    "PYTHOS:CORE:BOOT_VISUAL:FRAME",
    "PYTHOS:CORE:BOOT_SYNC:AUDIO",
    "PYTHOS:CORE:AUDIO_VISUAL_SYNC_READY",
]
GRACEFUL_AUDIO_FALLBACK_MARKERS = [
    "PYTHOS:CORE:AUDIO:FALLBACK_ARMED",
    "PYTHOS:CORE:GRACEFUL_AUDIO_FALLBACK_READY",
    "PYTHOS:CORE:PHASE_6_COMPLETE",
]
BLOCK_DEVICE_MARKERS = [
    "PYTHOS:CORE:BLOCK:DEVICE_SELECTED",
    "PYTHOS:CORE:BLOCK_DEVICE_READY",
]
STORAGE_SERVICE_MARKERS = [
    "PYTHOS:CORE:STORAGE:ACCESS_GRANTED",
    "PYTHOS:CORE:STORAGE:ACCESS_DENIED",
    "PYTHOS:CORE:STORAGE_SERVICE_READY",
]
APPEND_ONLY_JOURNAL_MARKERS = [
    "PYTHOS:CORE:STORAGE:JOURNAL_APPEND",
    "PYTHOS:CORE:APPEND_ONLY_JOURNAL_READY",
]
CHECKSUM_COMMIT_MARKERS = [
    "PYTHOS:CORE:STORAGE:CHECKSUM_VALID",
    "PYTHOS:CORE:STORAGE:COMMIT_MARKER",
    "PYTHOS:CORE:CHECKSUM_COMMIT_MARKERS_READY",
]
CRASH_RECOVERY_MARKERS = [
    "PYTHOS:CORE:STORAGE:RECOVERY_REPLAY",
    "PYTHOS:CORE:STORAGE:RECOVERY_ROLLBACK",
    "PYTHOS:CORE:CRASH_RECOVERY_READY",
]
TYPED_OBJECT_FORMAT_MARKERS = [
    "PYTHOS:CORE:OBJECT:STABLE_ID",
    "PYTHOS:CORE:OBJECT:VERSIONED_FIELDS",
    "PYTHOS:CORE:TYPED_OBJECT_FORMAT_READY",
]
OBJECT_RELATIONSHIP_MARKERS = [
    "PYTHOS:CORE:OBJECT:RELATIONSHIP",
    "PYTHOS:CORE:OBJECT:RELATIONSHIP_QUERY",
    "PYTHOS:CORE:OBJECT_RELATIONSHIPS_READY",
]
REVISION_HISTORY_MARKERS = [
    "PYTHOS:CORE:OBJECT:REVISION_RETAINED",
    "PYTHOS:CORE:OBJECT:REVISION_PROVENANCE",
    "PYTHOS:CORE:REVISION_HISTORY_READY",
]
WORKSPACE_OBJECT_MARKERS = [
    "PYTHOS:CORE:WORKSPACE:SESSION_OBJECT",
    "PYTHOS:CORE:WORKSPACE:WINDOW_LAYOUT",
    "PYTHOS:CORE:WORKSPACE_OBJECTS_READY",
]
AUDIO_DEVICE_ABSENT_MARKERS = [
    "PYTHOS:CORE:AUDIO:DEVICE_ABSENT",
    "PYTHOS:CORE:AUDIO_DEVICE_SELECTION_READY",
]
AUDIO_DRIVER_SKIPPED_MARKERS = [
    "PYTHOS:CORE:AUDIO:DRIVER_SKIPPED",
    "PYTHOS:CORE:AUDIO_DRIVER_READY",
]
AUDIO_BUFFER_SKIPPED_MARKERS = [
    "PYTHOS:CORE:AUDIO:BUFFER_SKIPPED",
    "PYTHOS:CORE:AUDIO_BUFFERS_READY",
]
PCM_PLAYBACK_SKIPPED_MARKERS = [
    "PYTHOS:CORE:AUDIO:PCM_SKIPPED",
    "PYTHOS:CORE:PCM_PLAYBACK_READY",
]
AUDIO_FALLBACK_TAKEN_MARKERS = [
    "PYTHOS:CORE:AUDIO:FALLBACK",
    "PYTHOS:CORE:GRACEFUL_AUDIO_FALLBACK_READY",
    "PYTHOS:CORE:PHASE_6_COMPLETE",
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    "PYTHOS:CORE:MILESTONE_1_COMPLETE",
]

SLICE_MARKERS["request-reply"] = SLICE_MARKERS["bounded-queues"] + REQUEST_REPLY_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    REQUEST_REPLY_MARKERS,
)
SLICE_MARKERS["capability-handles"] = (
    SLICE_MARKERS["request-reply"] + CAPABILITY_HANDLE_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    CAPABILITY_HANDLE_MARKERS,
)
SLICE_MARKERS["shared-memory-handles"] = (
    SLICE_MARKERS["capability-handles"] + SHARED_MEMORY_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    SHARED_MEMORY_MARKERS,
)
SLICE_MARKERS["permission-validation"] = (
    SLICE_MARKERS["shared-memory-handles"] + PERMISSION_VALIDATION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    PERMISSION_VALIDATION_MARKERS,
)
SLICE_MARKERS["revocation"] = SLICE_MARKERS["permission-validation"] + REVOCATION_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    REVOCATION_MARKERS,
)
SLICE_MARKERS["negative-authorization-tests"] = (
    SLICE_MARKERS["revocation"] + NEGATIVE_AUTHORIZATION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    NEGATIVE_AUTHORIZATION_MARKERS,
)
SLICE_MARKERS["audit-logging"] = (
    SLICE_MARKERS["negative-authorization-tests"] + AUDIT_LOGGING_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIT_LOGGING_MARKERS,
)
SLICE_MARKERS["runtime-selection"] = (
    SLICE_MARKERS["audit-logging"] + RUNTIME_SELECTION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    RUNTIME_SELECTION_MARKERS,
)
SLICE_MARKERS["init-pak-loading"] = (
    SLICE_MARKERS["runtime-selection"] + INIT_PAK_LOADING_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    INIT_PAK_LOADING_MARKERS,
)
SLICE_MARKERS["interpreter-boot"] = (
    SLICE_MARKERS["init-pak-loading"] + INTERPRETER_BOOT_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    INTERPRETER_BOOT_MARKERS,
)
SLICE_MARKERS["system-api-surface"] = (
    SLICE_MARKERS["interpreter-boot"] + SYSTEM_API_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    SYSTEM_API_MARKERS,
)
SLICE_MARKERS["value-validation"] = (
    SLICE_MARKERS["system-api-surface"] + VALUE_VALIDATION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    VALUE_VALIDATION_MARKERS,
)
SLICE_MARKERS["service-manager"] = (
    SLICE_MARKERS["value-validation"] + SERVICE_MANAGER_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    SERVICE_MANAGER_MARKERS,
)
SLICE_MARKERS["exception-containment"] = (
    SLICE_MARKERS["service-manager"] + EXCEPTION_CONTAINMENT_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    EXCEPTION_CONTAINMENT_MARKERS,
)
SLICE_MARKERS["service-restart"] = (
    SLICE_MARKERS["exception-containment"] + SERVICE_RESTART_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    SERVICE_RESTART_MARKERS,
)
SLICE_MARKERS["async-events"] = SLICE_MARKERS["service-restart"] + ASYNC_EVENT_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    ASYNC_EVENT_MARKERS,
)
SLICE_MARKERS["keyboard-driver"] = SLICE_MARKERS["async-events"] + INPUT_DRIVER_MARKERS
SLICE_MARKERS["mouse-driver"] = SLICE_MARKERS["keyboard-driver"]
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    INPUT_DRIVER_MARKERS,
)
SLICE_MARKERS["input-event-service"] = (
    SLICE_MARKERS["keyboard-driver"] + INPUT_EVENT_SERVICE_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    INPUT_EVENT_SERVICE_MARKERS,
)
SLICE_MARKERS["software-renderer"] = (
    SLICE_MARKERS["input-event-service"] + SOFTWARE_RENDERER_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    SOFTWARE_RENDERER_MARKERS,
)
SLICE_MARKERS["font-system"] = SLICE_MARKERS["software-renderer"] + FONT_SYSTEM_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    FONT_SYSTEM_MARKERS,
)
SLICE_MARKERS["compositor"] = SLICE_MARKERS["font-system"] + COMPOSITOR_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    COMPOSITOR_MARKERS,
)
SLICE_MARKERS["window-interaction"] = (
    SLICE_MARKERS["compositor"] + WINDOW_INTERACTION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    WINDOW_INTERACTION_MARKERS,
)
SLICE_MARKERS["widgets"] = SLICE_MARKERS["window-interaction"] + WIDGET_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    WIDGET_MARKERS,
)
SLICE_MARKERS["phase-5-complete"] = SLICE_MARKERS["widgets"] + PHASE_5_APP_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    PHASE_5_APP_MARKERS,
)
SLICE_MARKERS["audio-device-selection"] = (
    SLICE_MARKERS["phase-5-complete"] + AUDIO_DEVICE_SELECTION_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIO_DEVICE_SELECTION_MARKERS,
)
SLICE_MARKERS["audio-driver"] = (
    SLICE_MARKERS["audio-device-selection"] + AUDIO_DRIVER_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIO_DRIVER_MARKERS,
)
SLICE_MARKERS["audio-buffers"] = SLICE_MARKERS["audio-driver"] + AUDIO_BUFFER_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIO_BUFFER_MARKERS,
)
SLICE_MARKERS["pcm-playback"] = SLICE_MARKERS["audio-buffers"] + PCM_PLAYBACK_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    PCM_PLAYBACK_MARKERS,
)
SLICE_MARKERS["audio-mixing"] = SLICE_MARKERS["pcm-playback"] + AUDIO_MIXING_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIO_MIXING_MARKERS,
)
SLICE_MARKERS["boot-asset-storage"] = SLICE_MARKERS["audio-mixing"] + BOOT_ASSET_MARKERS
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    BOOT_ASSET_MARKERS,
)
SLICE_MARKERS["audio-visual-sync"] = (
    SLICE_MARKERS["boot-asset-storage"] + AUDIO_VISUAL_SYNC_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    AUDIO_VISUAL_SYNC_MARKERS,
)
SLICE_MARKERS["phase-6-complete"] = (
    SLICE_MARKERS["audio-visual-sync"] + GRACEFUL_AUDIO_FALLBACK_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    GRACEFUL_AUDIO_FALLBACK_MARKERS,
)
SLICE_MARKERS["block-device-driver"] = (
    SLICE_MARKERS["phase-6-complete"] + BLOCK_DEVICE_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    BLOCK_DEVICE_MARKERS,
)
SLICE_MARKERS["storage-service"] = (
    SLICE_MARKERS["block-device-driver"] + STORAGE_SERVICE_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    STORAGE_SERVICE_MARKERS,
)
SLICE_MARKERS["append-only-journal"] = (
    SLICE_MARKERS["storage-service"] + APPEND_ONLY_JOURNAL_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    APPEND_ONLY_JOURNAL_MARKERS,
)
SLICE_MARKERS["checksums-and-commit-markers"] = (
    SLICE_MARKERS["append-only-journal"] + CHECKSUM_COMMIT_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    CHECKSUM_COMMIT_MARKERS,
)
SLICE_MARKERS["crash-recovery"] = (
    SLICE_MARKERS["checksums-and-commit-markers"] + CRASH_RECOVERY_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    CRASH_RECOVERY_MARKERS,
)
SLICE_MARKERS["typed-object-format"] = (
    SLICE_MARKERS["crash-recovery"] + TYPED_OBJECT_FORMAT_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    TYPED_OBJECT_FORMAT_MARKERS,
)
SLICE_MARKERS["object-relationships"] = (
    SLICE_MARKERS["typed-object-format"] + OBJECT_RELATIONSHIP_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    OBJECT_RELATIONSHIP_MARKERS,
)
SLICE_MARKERS["revision-history"] = (
    SLICE_MARKERS["object-relationships"] + REVISION_HISTORY_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    REVISION_HISTORY_MARKERS,
)
SLICE_MARKERS["workspace-objects"] = (
    SLICE_MARKERS["revision-history"] + WORKSPACE_OBJECT_MARKERS
)
SLICE_MARKERS["milestone-1"] = insert_before(
    SLICE_MARKERS["milestone-1"],
    "PYTHOS:CORE:FRAMEBUFFER_READY",
    WORKSPACE_OBJECT_MARKERS,
)
SLICE_MARKERS["graceful-audio-fallback"] = (
    SLICE_MARKERS["phase-5-complete"]
    + AUDIO_DEVICE_ABSENT_MARKERS
    + AUDIO_DRIVER_SKIPPED_MARKERS
    + AUDIO_BUFFER_SKIPPED_MARKERS
    + PCM_PLAYBACK_SKIPPED_MARKERS
    + AUDIO_MIXING_MARKERS
    + BOOT_ASSET_MARKERS
    + AUDIO_VISUAL_SYNC_MARKERS
    + AUDIO_FALLBACK_TAKEN_MARKERS
)


def run(command: list[str]) -> None:
    print("+ " + " ".join(command))
    subprocess.run(command, cwd=ROOT, check=True)


def default_qemu_timeout() -> float | None:
    value = os.environ.get("PYTHOS_TEST_BOOT_TIMEOUT")
    return float(value) if value else None


def qemu_timeout_args(timeout: float | None) -> list[str]:
    return [] if timeout is None else ["--timeout", str(timeout)]


def assert_markers(serial: str, expected: list[str]) -> None:
    for failure in FAILURE_MARKERS:
        if failure in serial:
            raise AssertionError(f"failure marker present: {failure}")

    cursor = 0
    for marker in expected:
        index = serial.find(marker, cursor)
        if index == -1:
            raise AssertionError(f"missing or out-of-order marker: {marker}\nserial:\n{serial}")
        cursor = index + len(marker)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--slice", choices=sorted(SLICE_MARKERS), default="loader-enter")
    parser.add_argument("--media", choices=["esp", "iso"], default="esp")
    parser.add_argument("--no-audio-device", action="store_true")
    parser.add_argument("--timeout", type=float, default=default_qemu_timeout())
    args = parser.parse_args()
    timeout_args = qemu_timeout_args(args.timeout)

    run(["cargo", "build", "-p", "pythos-boot", "--target", "x86_64-unknown-uefi"])
    run(["cargo", "build", "-p", "pythos-core", "--target", "x86_64-unknown-none"])
    if args.media == "iso":
        run([sys.executable, "scripts/build-iso.py", "--output", str(ISO_IMAGE)])
        run(
            [
                sys.executable,
                "scripts/run-qemu.py",
                "--iso",
                str(ISO_IMAGE),
                "--serial-log",
                str(SERIAL_LOG),
                "--expect-outcome",
                "success",
            ]
            + timeout_args
            + (["--no-audio-device"] if args.no_audio_device else [])
        )
    else:
        run([sys.executable, "scripts/build-image.py"])
        run(
            [
                sys.executable,
                "scripts/run-qemu.py",
                "--serial-log",
                str(SERIAL_LOG),
                "--expect-outcome",
                "success",
            ]
            + timeout_args
            + (["--no-audio-device"] if args.no_audio_device else [])
        )

    serial = SERIAL_LOG.read_text(encoding="utf-8", errors="replace")
    try:
        assert_markers(serial, SLICE_MARKERS[args.slice])
    except AssertionError as error:
        print(f"BOOT_TEST_OUTCOME marker-order-violation\n{error}", file=sys.stderr)
        return MARKER_ORDER_EXIT_CODE
    print("BOOT_TEST_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
