//! Private acceptance markers for the bounded Phase 14 secure-transport proof.

pub const SECURE_BOOTSTRAPPED_MARKER: &str = "PYTHOS:CORE:SECURE:BOOTSTRAPPED";
pub const SECURE_OPEN_GRANTED_MARKER: &str = "PYTHOS:CORE:SECURE:OPEN_GRANTED";
pub const SECURE_TCP_READY_MARKER: &str = "PYTHOS:CORE:SECURE:TCP_READY";
pub const SECURE_TLS_HANDSHAKE_OK_MARKER: &str = "PYTHOS:CORE:SECURE:TLS_HANDSHAKE_OK";
pub const SECURE_REQUEST_ENCRYPTED_MARKER: &str = "PYTHOS:CORE:SECURE:REQUEST_ENCRYPTED";
pub const SECURE_RESPONSE_DECRYPTED_MARKER: &str = "PYTHOS:CORE:SECURE:RESPONSE_DECRYPTED";
pub const SECURE_CLOSE_OK_MARKER: &str = "PYTHOS:CORE:SECURE:CLOSE_OK";
pub const SECURE_TEARDOWN_REVOKED_MARKER: &str = "PYTHOS:CORE:SECURE:TEARDOWN_REVOKED";
pub const SECURE_READY_MARKER: &str = "PYTHOS:CORE:SECURE_READY";

pub const SECURE_TAMPER_REJECTED_MARKER: &str = "PYTHOS:CORE:SECURE:TAMPER_REJECTED";
pub const SECURE_TAMPER_READY_MARKER: &str = "PYTHOS:CORE:SECURE_TAMPER_READY";

pub const SECURE_DENIED_BOOTSTRAPPED_MARKER: &str = "PYTHOS:CORE:SECURE:DENIED_BOOTSTRAPPED";
pub const SECURE_OPEN_WITHOUT_CAP_DENIED_MARKER: &str =
    "PYTHOS:CORE:SECURE:OPEN_WITHOUT_CAP_DENIED";
pub const SECURE_DENIED_TEARDOWN_COMPLETE_MARKER: &str =
    "PYTHOS:CORE:SECURE:DENIED_TEARDOWN_COMPLETE";
pub const SECURE_DENIED_READY_MARKER: &str = "PYTHOS:CORE:SECURE_DENIED_READY";

pub const SECURE_GRANTED_MARKERS: [&str; 9] = [
    SECURE_BOOTSTRAPPED_MARKER,
    SECURE_OPEN_GRANTED_MARKER,
    SECURE_TCP_READY_MARKER,
    SECURE_TLS_HANDSHAKE_OK_MARKER,
    SECURE_REQUEST_ENCRYPTED_MARKER,
    SECURE_RESPONSE_DECRYPTED_MARKER,
    SECURE_CLOSE_OK_MARKER,
    SECURE_TEARDOWN_REVOKED_MARKER,
    SECURE_READY_MARKER,
];

pub const SECURE_TAMPER_MARKERS: [&str; 8] = [
    SECURE_BOOTSTRAPPED_MARKER,
    SECURE_OPEN_GRANTED_MARKER,
    SECURE_TCP_READY_MARKER,
    SECURE_TLS_HANDSHAKE_OK_MARKER,
    SECURE_REQUEST_ENCRYPTED_MARKER,
    SECURE_TAMPER_REJECTED_MARKER,
    SECURE_TEARDOWN_REVOKED_MARKER,
    SECURE_TAMPER_READY_MARKER,
];

pub const SECURE_DENIED_MARKERS: [&str; 4] = [
    SECURE_DENIED_BOOTSTRAPPED_MARKER,
    SECURE_OPEN_WITHOUT_CAP_DENIED_MARKER,
    SECURE_DENIED_TEARDOWN_COMPLETE_MARKER,
    SECURE_DENIED_READY_MARKER,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_sequences_are_frozen_and_unique() {
        for markers in [
            SECURE_GRANTED_MARKERS.as_slice(),
            SECURE_TAMPER_MARKERS.as_slice(),
            SECURE_DENIED_MARKERS.as_slice(),
        ] {
            for (index, marker) in markers.iter().enumerate() {
                assert!(!markers[..index].contains(marker));
            }
        }
        assert_eq!(SECURE_READY_MARKER, "PYTHOS:CORE:SECURE_READY");
        assert_eq!(
            SECURE_TAMPER_READY_MARKER,
            "PYTHOS:CORE:SECURE_TAMPER_READY"
        );
        assert_eq!(
            SECURE_DENIED_READY_MARKER,
            "PYTHOS:CORE:SECURE_DENIED_READY"
        );
    }
}
